// porirua_directory/directus/extensions/directory-editor/src/module/pin-map.vue
<template>
  <div class="pin-map" :class="{ compare: Boolean(comparePoint) }" role="application" :aria-label="ariaLabel">
    <div ref="el" class="pin-map-canvas directory-pin-map-canvas"></div>
    <p v-if="comparePoint" class="pin-legend">
      <span>Now — on the site</span>
      <span>Proposed — this update</span>
    </p>
    <p class="sr-only">{{ ariaLabel }}</p>
  </div>
</template>

<script>
import L from "leaflet";
import "leaflet/dist/leaflet.css";

const PORIRUA = { lat: -41.134, lng: 174.84, zoom: 12 };
const TILES = "https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png";
const ABSENCE_MS = 3000;

function asCoord(value) {
  if (value == null || value === "") return null;
  const n = Number(value);
  return Number.isFinite(n) ? n : null;
}

function pointFrom(lat, lng) {
  const resolvedLat = asCoord(lat);
  const resolvedLng = asCoord(lng);
  if (resolvedLat == null || resolvedLng == null) return null;
  return { lat: resolvedLat, lng: resolvedLng };
}

function pinIcon(kind, label) {
  return L.divIcon({
    className: `directory-pin directory-pin-${kind}`,
    html: `<span class="directory-pin-caption">${label}</span><span class="directory-pin-dot"></span>`,
    iconSize: [72, 36],
    iconAnchor: [36, 34],
  });
}

function mapHasUsableSize(el) {
  return Boolean(el && el.clientWidth >= 40 && el.clientHeight >= 40);
}

export default {
  props: {
    lat: { type: [Number, String], default: null },
    lng: { type: [Number, String], default: null },
    compareLat: { type: [Number, String], default: null },
    compareLng: { type: [Number, String], default: null },
    draggable: { type: Boolean, default: false },
  },
  emits: ["move", "tiles-failed"],
  data() {
    return {
      map: null,
      tiles: null,
      marker: null,
      compareMarker: null,
      resizeObserver: null,
      sized: false,
      tilesLoaded: 0,
      tilesFailed: false,
      absenceTimer: null,
      absenceWatching: false,
    };
  },
  computed: {
    point() {
      return pointFrom(this.lat, this.lng);
    },
    comparePoint() {
      const next = pointFrom(this.compareLat, this.compareLng);
      if (!next || !this.point) return null;
      if (next.lat === this.point.lat && next.lng === this.point.lng) return null;
      return next;
    },
    ariaLabel() {
      if (this.draggable) return "Map pin. Drag the pin if the place is wrong.";
      if (this.comparePoint) {
        return "Map showing the current pin and the proposed pin. Now is on the site. Proposed is this update.";
      }
      return "Map pin for this listing.";
    },
  },
  watch: {
    point: {
      deep: true,
      handler() {
        this.syncMarkers();
      },
    },
    comparePoint: {
      deep: true,
      handler() {
        this.syncMarkers();
      },
    },
    draggable() {
      if (this.marker) this.marker.dragging?.[this.draggable ? "enable" : "disable"]?.();
    },
  },
  mounted() {
    this.map = L.map(this.$refs.el, {
      scrollWheelZoom: false,
      zoomControl: true,
    }).setView([PORIRUA.lat, PORIRUA.lng], PORIRUA.zoom);
    this.tiles = L.tileLayer(TILES, {
      attribution: "&copy; OpenStreetMap",
      maxZoom: 19,
    });
    this.tiles.on("tileload", () => {
      this.tilesLoaded += 1;
    });
    this.tiles.on("tileerror", () => this.failTiles());
    this.tiles.addTo(this.map);
    this.syncMarkers();
    if (this.draggable) {
      this.map.on("click", (event) => {
        this.$emit("move", { lat: event.latlng.lat, lng: event.latlng.lng });
      });
    }
    this.resizeObserver = new ResizeObserver(() => {
      this.syncViewport();
    });
    this.resizeObserver.observe(this.$refs.el);
    this.$nextTick(() => {
      requestAnimationFrame(() => {
        requestAnimationFrame(() => this.syncViewport());
      });
    });
  },
  beforeUnmount() {
    this.clearAbsenceTimer();
    this.resizeObserver?.disconnect();
    this.resizeObserver = null;
    this.map?.remove();
    this.map = null;
    this.tiles = null;
    this.marker = null;
    this.compareMarker = null;
  },
  methods: {
    failTiles() {
      if (this.tilesFailed) return;
      this.tilesFailed = true;
      this.clearAbsenceTimer();
      this.$emit("tiles-failed");
    },
    clearAbsenceTimer() {
      if (this.absenceTimer) {
        clearTimeout(this.absenceTimer);
        this.absenceTimer = null;
      }
    },
    startAbsenceWatch() {
      if (this.absenceWatching || this.tilesFailed) return;
      this.absenceWatching = true;
      this.absenceTimer = setTimeout(() => {
        this.absenceTimer = null;
        if (this.tilesFailed) return;
        if (!mapHasUsableSize(this.$refs.el)) {
          this.absenceWatching = false;
          return;
        }
        if (this.tilesLoaded === 0) this.failTiles();
      }, ABSENCE_MS);
    },
    syncViewport() {
      if (!this.map || !this.$refs.el) return;
      if (!mapHasUsableSize(this.$refs.el)) return;
      this.map.invalidateSize();
      if (!this.sized) {
        this.sized = true;
        this.fitView();
      }
      this.startAbsenceWatch();
    },
    upsertMarker(existing, point, { kind, label, draggable }) {
      if (!point) {
        existing?.remove();
        return null;
      }
      const latlng = [point.lat, point.lng];
      if (!existing) {
        const marker = L.marker(latlng, {
          draggable,
          keyboard: true,
          title: label,
          icon: pinIcon(kind, label),
        }).addTo(this.map);
        if (draggable) {
          marker.on("dragend", () => {
            const next = marker.getLatLng();
            this.$emit("move", { lat: next.lat, lng: next.lng });
          });
        }
        return marker;
      }
      existing.setLatLng(latlng);
      existing.dragging?.[draggable ? "enable" : "disable"]?.();
      return existing;
    },
    syncMarkers() {
      if (!this.map) return;
      this.marker = this.upsertMarker(this.marker, this.point, {
        kind: this.comparePoint ? "now" : "single",
        label: this.comparePoint ? "Now" : this.ariaLabel,
        draggable: this.draggable,
      });
      this.compareMarker = this.upsertMarker(this.compareMarker, this.comparePoint, {
        kind: "proposed",
        label: "Proposed",
        draggable: false,
      });
      this.fitView();
    },
    fitView() {
      if (!this.map) return;
      if (this.point && this.comparePoint) {
        this.map.fitBounds([
          [this.point.lat, this.point.lng],
          [this.comparePoint.lat, this.comparePoint.lng],
        ], { padding: [28, 28], maxZoom: 16 });
        return;
      }
      if (this.point) {
        this.map.setView([this.point.lat, this.point.lng], Math.max(this.map.getZoom() || 0, 16));
        return;
      }
      this.map.setView([PORIRUA.lat, PORIRUA.lng], PORIRUA.zoom);
    },
  },
};
</script>

<style>
@import "leaflet/dist/leaflet.css";

.directory-pin-map-canvas.leaflet-container {
  width: 100% !important;
  height: 160px !important;
  min-height: 160px !important;
  background: #ddd;
}
.pin-map.compare .directory-pin-map-canvas.leaflet-container {
  height: 200px !important;
  min-height: 200px !important;
}
.directory-pin-map-canvas.leaflet-container img.leaflet-tile {
  mix-blend-mode: normal !important;
  max-width: none !important;
  max-height: none !important;
}
</style>

<style scoped>
.pin-map {
  flex: 1 1 100%;
  width: 100%;
  min-width: 100%;
  min-height: 160px;
}
.pin-map-canvas {
  width: 100%;
  height: 160px;
  min-height: 160px;
  border-radius: 8px;
  z-index: 1;
  background: #ddd;
}
.pin-map.compare .pin-map-canvas {
  height: 200px;
  min-height: 200px;
}
.pin-legend {
  display: flex;
  flex-wrap: wrap;
  gap: 8px 16px;
  margin: 6px 0 0;
  font-size: 0.85rem;
  color: var(--theme--foreground);
}
.sr-only {
  position: absolute;
  width: 1px;
  height: 1px;
  overflow: hidden;
  clip: rect(0 0 0 0);
}
</style>

<style>
.directory-pin {
  background: transparent;
  border: 0;
  text-align: center;
}
.directory-pin-caption {
  display: block;
  font: 600 11px/1.2 system-ui, sans-serif;
  color: var(--theme--foreground, #172940);
  text-shadow: 0 0 3px #fff, 0 0 3px #fff;
}
.directory-pin-dot {
  display: block;
  width: 18px;
  height: 18px;
  margin: 2px auto 0;
  border-radius: 50% 50% 50% 0;
  transform: rotate(-45deg);
  background: var(--theme--primary, #6644ff);
  box-shadow: 0 1px 4px rgba(0, 0, 0, 0.35);
}
.directory-pin-now .directory-pin-dot {
  background: #fff;
  border: 3px solid var(--theme--foreground, #172940);
  box-sizing: border-box;
}
.directory-pin-proposed .directory-pin-dot {
  background: var(--theme--primary, #6644ff);
}
</style>

// porirua_directory/payload/src/directory/PinMap.tsx
"use client";

import { useEffect, useRef } from "react";
import type { Map as LeafletMap, Marker, TileLayer } from "leaflet";
import "leaflet/dist/leaflet.css";

const PORIRUA = { lat: -41.134, lng: 174.84, zoom: 12 };
const TILES = "https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png";
const ABSENCE_MS = 3000;

export type Pin = { lat: number; lng: number };

export type PinMapProps = {
  pin?: Pin | null;
  comparePin?: Pin | null;
  draggable?: boolean;
  onMove?: (pin: Pin) => void;
  onTilesFailed?: () => void;
};

function samePin(a?: Pin | null, b?: Pin | null) {
  if (!a || !b) return a === b;
  return a.lat === b.lat && a.lng === b.lng;
}

// A pane narrower than a tile renders grey, so wait for a real size before
// fitting the view or judging whether tiles arrived.
function hasUsableSize(el: HTMLElement | null) {
  return Boolean(el && el.clientWidth >= 40 && el.clientHeight >= 40);
}

function ariaLabelFor(draggable: boolean, comparePin?: Pin | null) {
  if (draggable) return "Map pin. Drag the pin if the place is wrong.";
  if (comparePin) {
    return "Map showing the current pin and the proposed pin. Now is on the site. Proposed is this update.";
  }
  return "Map pin for this listing.";
}

export function PinMap({ pin = null, comparePin = null, draggable = false, onMove, onTilesFailed }: PinMapProps) {
  const canvasRef = useRef<HTMLDivElement>(null);
  const mapRef = useRef<LeafletMap | null>(null);
  const markerRef = useRef<Marker | null>(null);
  const compareMarkerRef = useRef<Marker | null>(null);
  // Callbacks and pins are read through refs so the map is built once and then
  // updated in place, rather than torn down on every parent render.
  const onMoveRef = useRef(onMove);
  const onTilesFailedRef = useRef(onTilesFailed);
  const stateRef = useRef({ pin, comparePin, draggable });

  onMoveRef.current = onMove;
  onTilesFailedRef.current = onTilesFailed;

  const shownCompare = samePin(pin, comparePin) ? null : comparePin;
  const label = ariaLabelFor(draggable, shownCompare);

  useEffect(() => {
    let cancelled = false;
    let cleanup: (() => void) | undefined;

    // Leaflet touches window at import time, so it is only pulled in here.
    void import("leaflet").then(({ default: L }) => {
      const canvas = canvasRef.current;
      if (cancelled || !canvas || mapRef.current) return;

      const map = L.map(canvas, { scrollWheelZoom: false, zoomControl: true }).setView(
        [PORIRUA.lat, PORIRUA.lng],
        PORIRUA.zoom
      );
      mapRef.current = map;

      let tilesLoaded = 0;
      let tilesFailed = false;
      let absenceTimer: ReturnType<typeof setTimeout> | null = null;
      let sized = false;

      const failTiles = () => {
        if (tilesFailed) return;
        tilesFailed = true;
        if (absenceTimer) clearTimeout(absenceTimer);
        absenceTimer = null;
        onTilesFailedRef.current?.();
      };

      const tiles: TileLayer = L.tileLayer(TILES, {
        attribution: "&copy; OpenStreetMap",
        maxZoom: 19,
      });
      tiles.on("tileload", () => {
        tilesLoaded += 1;
      });
      tiles.on("tileerror", failTiles);
      tiles.addTo(map);

      const pinIcon = (kind: string, caption: string) =>
        L.divIcon({
          className: `directory-pin directory-pin-${kind}`,
          html: `<span class="directory-pin-caption">${caption}</span><span class="directory-pin-dot"></span>`,
          iconSize: [72, 36],
          iconAnchor: [36, 34],
        });

      const fitView = () => {
        const { pin: current, comparePin: compare } = stateRef.current;
        const other = samePin(current, compare) ? null : compare;
        if (current && other) {
          map.fitBounds(
            [
              [current.lat, current.lng],
              [other.lat, other.lng],
            ],
            { padding: [28, 28], maxZoom: 16 }
          );
          return;
        }
        if (current) {
          map.setView([current.lat, current.lng], Math.max(map.getZoom() || 0, 16));
          return;
        }
        map.setView([PORIRUA.lat, PORIRUA.lng], PORIRUA.zoom);
      };

      const upsert = (
        existing: Marker | null,
        point: Pin | null,
        options: { kind: string; caption: string; canDrag: boolean }
      ) => {
        if (!point) {
          existing?.remove();
          return null;
        }
        const latlng: [number, number] = [point.lat, point.lng];
        if (existing) {
          existing.setLatLng(latlng);
          if (options.canDrag) existing.dragging?.enable();
          else existing.dragging?.disable();
          return existing;
        }
        const marker = L.marker(latlng, {
          draggable: options.canDrag,
          keyboard: true,
          title: options.caption,
          icon: pinIcon(options.kind, options.caption),
        }).addTo(map);
        if (options.canDrag) {
          marker.on("dragend", () => {
            const next = marker.getLatLng();
            onMoveRef.current?.({ lat: next.lat, lng: next.lng });
          });
        }
        return marker;
      };

      const syncMarkers = () => {
        const { pin: current, comparePin: compare, draggable: canDrag } = stateRef.current;
        const other = samePin(current, compare) ? null : compare;
        markerRef.current = upsert(markerRef.current, current, {
          kind: other ? "now" : "single",
          caption: other ? "Now" : "Pin",
          canDrag,
        });
        compareMarkerRef.current = upsert(compareMarkerRef.current, other, {
          kind: "proposed",
          caption: "Proposed",
          canDrag: false,
        });
        fitView();
      };

      // The map is often built inside a panel that is still laying out, so
      // Leaflet must be told the size once the pane is really on screen.
      const syncViewport = () => {
        if (!hasUsableSize(canvas)) return;
        map.invalidateSize();
        if (!sized) {
          sized = true;
          fitView();
        }
        if (absenceTimer || tilesFailed) return;
        absenceTimer = setTimeout(() => {
          absenceTimer = null;
          if (tilesFailed || !hasUsableSize(canvas)) return;
          if (tilesLoaded === 0) failTiles();
        }, ABSENCE_MS);
      };

      if (draggable) {
        map.on("click", (event) => {
          onMoveRef.current?.({ lat: event.latlng.lat, lng: event.latlng.lng });
        });
      }

      syncMarkers();
      const observer = new ResizeObserver(() => syncViewport());
      observer.observe(canvas);
      requestAnimationFrame(() => requestAnimationFrame(() => syncViewport()));

      (map as LeafletMap & { __syncMarkers?: () => void }).__syncMarkers = syncMarkers;

      cleanup = () => {
        if (absenceTimer) clearTimeout(absenceTimer);
        observer.disconnect();
        map.remove();
      };
    });

    return () => {
      cancelled = true;
      cleanup?.();
      mapRef.current = null;
      markerRef.current = null;
      compareMarkerRef.current = null;
    };
  }, []);

  useEffect(() => {
    stateRef.current = { pin, comparePin, draggable };
    const map = mapRef.current as (LeafletMap & { __syncMarkers?: () => void }) | null;
    map?.__syncMarkers?.();
  }, [pin?.lat, pin?.lng, comparePin?.lat, comparePin?.lng, draggable]);

  return (
    <div className={shownCompare ? "pin-map compare" : "pin-map"} role="application" aria-label={label}>
      <div ref={canvasRef} className="pin-map-canvas" />
      {shownCompare ? (
        <p className="pin-legend">
          <span>Now — on the site</span>
          <span>Proposed — this update</span>
        </p>
      ) : null}
    </div>
  );
}
