// porirua_directory/directus/extensions/directory-editor/src/module/verification-bar.vue
<template>
  <div class="verify">
    <a
      v-if="website"
      class="verify-link"
      :href="website"
      target="_blank"
      rel="noopener noreferrer"
    >Website</a>
    <a v-if="phone" class="verify-link" :href="'tel:' + phone">{{ phone }}</a>
    <p v-if="address" class="verify-address">
      <span v-if="addressNote" class="verify-note">{{ addressNote }}</span>
      {{ address }}
    </p>
    <pin-map v-if="showMap && pin && !tilesFailed" :lat="pin.lat" :lng="pin.lng" @tiles-failed="tilesFailed = true" />
  </div>
</template>

<script>
import PinMap from "./pin-map.vue";

export default {
  components: { PinMap },
  props: {
    website: { type: String, default: "" },
    phone: { type: String, default: "" },
    address: { type: String, default: "" },
    addressNote: { type: String, default: "" },
    pin: { type: Object, default: null },
    showMap: { type: Boolean, default: false },
  },
  data() {
    return { tilesFailed: false };
  },
  watch: {
    pin() {
      this.tilesFailed = false;
    },
  },
};
</script>

<style scoped>
.verify {
  display: flex;
  flex-wrap: wrap;
  gap: 8px 16px;
  align-items: center;
  margin: 12px 0 4px;
}
.verify-link {
  color: var(--theme--primary);
}
.verify-address {
  margin: 0;
  width: 100%;
}
.verify-note {
  display: block;
  color: var(--theme--foreground-subdued);
  font-size: 0.85rem;
}
</style>

// porirua_directory/payload/src/directory/VerificationBar.tsx
"use client";

import type { VerificationBarProps } from "./types";

export function VerificationBar({ model }: VerificationBarProps) {
  return (
    <div className="verify">
      {model.websiteHidden ? null : (
        <a
          className="verify-link"
          href={model.websiteHref}
          target={model.websiteTarget}
          rel={model.websiteRel}
          tabIndex={model.websiteTabIndex}
        >
          Website
        </a>
      )}
      {model.phone ? (
        <a className="verify-link" href={model.telHref}>
          {model.phone}
        </a>
      ) : null}
      {model.address ? (
        <p className="verify-address">
          {model.addressNote ? <span className="verify-note">{model.addressNote}</span> : null}
          {model.address}
        </p>
      ) : null}
      {model.showMap && model.pin ? (
        <div className="verify-map" data-lat={model.pin.lat} data-lng={model.pin.lng}>
          Map pin
        </div>
      ) : null}
    </div>
  );
}
